language: node_js
node_js:
- '6'
env:
- NODE_ENV=development
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
before_install:
  - git submodule update --init --recursive
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
install:
- npm install
- npm install mishoo/UglifyJS2#harmony
before_script:
- npm run lint
- sleep 15
script:
- npm run build-dev
- npm run build
sudo: required
notifications:
  email:
  - michael.l.dangelo@gmail.com
git:
  depth: 10
cache:
  directories:
  - node_modules
